#!/usr/bin/env bash

################################################################################
# Build Post Run Script for Seqera Platform Workflows
# 
# This script generates a post-run script that copies workflow outputs from
# the compute environment launch directory back to the project directory.
#
# Usage:
#   build_post_run_script.sh <NXF_LAUNCH_DIR> <WORKFLOW_RUN_ID> <NXF_OUTPUT_DIR_RUN_SPECIFIC> [OUTPUT_FILE]
#
# Arguments:
#   NXF_LAUNCH_DIR              - Launch directory on compute environment (where Tower stores run outputs)
#   WORKFLOW_RUN_ID              - Unique workflow run ID from Tower
#   NXF_OUTPUT_DIR_RUN_SPECIFIC - Target directory in project where outputs should be copied
#   OUTPUT_FILE                  - Optional: Path to output script file (default: stdout)
#
# Example:
#   build_post_run_script.sh \
#     "/ibex/scratch/projects/c2303/.tower-launches" \
#     "2KeMKH4y3dTelZ" \
#     "OUTPUTS/20251123_161010/TEST_RUN_1" \
#     "TMP/TEST_RUN_1.post_run_script.sh"
################################################################################

set -euo pipefail

# Check if required arguments are provided
if [ $# -lt 3 ]; then
    echo "Error: Missing required arguments" >&2
    echo "Usage: $0 <NXF_LAUNCH_DIR> <WORKFLOW_RUN_ID> <NXF_OUTPUT_DIR_RUN_SPECIFIC> [OUTPUT_FILE]" >&2
    exit 1
fi

NXF_LAUNCH_DIR="$1"
WORKFLOW_RUN_ID="$2"
NXF_OUTPUT_DIR_RUN_SPECIFIC="$3"
OUTPUT_FILE="${4:-}"

# Validate that required variables are not empty
if [ -z "$NXF_LAUNCH_DIR" ]; then
    echo "Error: NXF_LAUNCH_DIR cannot be empty" >&2
    exit 1
fi

if [ -z "$WORKFLOW_RUN_ID" ]; then
    echo "Error: WORKFLOW_RUN_ID cannot be empty" >&2
    exit 1
fi

if [ -z "$NXF_OUTPUT_DIR_RUN_SPECIFIC" ]; then
    echo "Error: NXF_OUTPUT_DIR_RUN_SPECIFIC cannot be empty" >&2
    exit 1
fi

# Build the post run script content
# Note: The glob pattern is not quoted to allow shell expansion
POST_RUN_SCRIPT_CONTENT=$(cat <<EOF
#!/usr/bin/env bash
# Post-run script generated by build_post_run_script.sh
# Copies workflow outputs from compute environment launch directory to project directory

# Copy all files/directories matching the workflow run ID from launch directory to output directory
mkdir -p "$NXF_OUTPUT_DIR_RUN_SPECIFIC"
cp ${NXF_LAUNCH_DIR}/*${WORKFLOW_RUN_ID}* "$NXF_OUTPUT_DIR_RUN_SPECIFIC"
EOF
)

# Output the script content
if [ -n "$OUTPUT_FILE" ]; then
    # Write to file
    echo "$POST_RUN_SCRIPT_CONTENT" > "$OUTPUT_FILE"
    chmod +x "$OUTPUT_FILE"
    echo "Post-run script written to: $OUTPUT_FILE" >&2
else
    # Output to stdout
    echo "$POST_RUN_SCRIPT_CONTENT"
fi

echo "Built post-run script: $OUTPUT_FILE"