#!/usr/bin/env bash

################################################################################
# Build Post Run Callback Script for Seqera Platform Workflows
# 
# This script generates a callback script that executes the post-run script.
# The callback script is used by Tower's --post-run flag to trigger the
# actual post-run script after workflow completion.
#
# Usage:
#   build_post_run_callback_script.sh <POST_RUN_SCRIPT> [OUTPUT_FILE]
#
# Arguments:
#   POST_RUN_SCRIPT - Path to the post-run script that will be executed
#   OUTPUT_FILE     - Optional: Path to output callback script file (default: stdout)
#
# Example:
#   build_post_run_callback_script.sh \
#     "TMP/TEST_RUN_1_20251123_161010.post_run_script.sh" \
#     "TMP/TEST_RUN_1_20251123_161010.post_run_script_callback.sh"
################################################################################

set -euo pipefail

# Check if required arguments are provided
if [ $# -lt 1 ]; then
    echo "Error: Missing required arguments" >&2
    echo "Usage: $0 <POST_RUN_SCRIPT> [OUTPUT_FILE]" >&2
    exit 1
fi

POST_RUN_SCRIPT="$1"
OUTPUT_FILE="${2:-}"

# Validate that required variables are not empty
if [ -z "$POST_RUN_SCRIPT" ]; then
    echo "Error: POST_RUN_SCRIPT cannot be empty" >&2
    exit 1
fi

# Build the callback script content
CALLBACK_SCRIPT_CONTENT=$(cat <<EOF
#!/usr/bin/env bash
# Post-run callback script generated by build_post_run_callback_script.sh
# This script is executed by Tower after workflow completion and runs the actual post-run script

bash "${POST_RUN_SCRIPT}"
EOF
)

# Output the script content
if [ -n "$OUTPUT_FILE" ]; then
    # Write to file
    echo "$CALLBACK_SCRIPT_CONTENT" > "$OUTPUT_FILE"
    chmod +x "$OUTPUT_FILE"
    echo "Callback script written to: $OUTPUT_FILE" >&2
else
    # Output to stdout
    echo "$CALLBACK_SCRIPT_CONTENT"
fi

echo "Built post-run callback script: $OUTPUT_FILE"